### ISSUE TITLE
Possible an issue with node 0.12

### ISSUE THREAD

**Issue by Globegitter** [sgress454/sails-hook-autoreload#13]
https://gist.github.com/bsocius/2f721e0b69334b542a91

Will look into this more and update if it actually is an issue with this hook, with chokidar or something else :)
Might also be an issue with the machine being used itself and the number of files being watched:
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by Globegitter** [comment]
Ok turned out to be an environment issue

**Comment by sgress454** [comment]
That's the kind of issue I like to see!  Keep 'em coming! :smile:
