### ISSUE TITLE
Unable to configure the hook

### ISSUE THREAD

**Issue by bostrom** [sgress454/sails-hook-autoreload#14]
There's a high risk that I just don't know Sails well enough, but I seem to be unable to configure the hook to include more directories to watch for changes. 

I've created the file `[my-sails-proj]/config/autoreload.js` with the following contents:

``` javascript
module.exports.autoreload = {
  active: true,
  dirs: [
    "api/models",
    "api/controllers",
    "api/responses"
  ]
};
```

But still Sails doesn't seem to be reacting to changes in my `responses` directory. The other two work fine, though.
Am I doing something wrong?

**Comment by sgress454** [comment]
Your expectations may be off--adding a new directory should trigger autoreload when files change in that directory, but it won't necessarily _reload_ those files.  Currently the autoreload hook only supports actually reloading the following components:
- Controllers (including model blueprints)
- Models
- Services

If you add `api/responses` to the watch list, then those three things will be reloaded whenever files in the `api/responses` folder change, but the responses won't actually be reloaded.  If you think that sounds sort of useless, you're right: the config option is there more to allow you to restrict things than to add them.  In the future it might be put to better use.  Also, there's a [pull request](https://github.com/sgress454/sails-hook-autoreload/pull/12) for adding responses and policies to the mix, but it fell into the same trap you did: perhaps the two if you could team up?

**Comment by bostrom** [comment]
Ah, I see. Thanks for the explanation. It might be a good Idea to update the README to include this information. I might throw you a PR later proposing some changes to it.
