### ISSUE TITLE
findOne not working

### ISSUE THREAD

**Issue by isuvorov** [sgress454/sails-hook-autoreload#18]
Something strange..
after autoreload  routes like "GET /model/:id"  throw 404 

but:
GET /model
POST /model
PUT /model/:id
DELETE /model/:id

works fine

**Comment by Globegitter** [comment]
Yep I am just experiencing the same thing. Here is the verbose logging:
![screen shot 2015-04-16 at 13 46 34](https://cloud.githubusercontent.com/assets/2580254/7181025/17d049b0-e43f-11e4-9435-3269a2c44a39.png)

**Comment by sgress454** [comment]
I'm guessing this is an issue with Sails, not the hook (since the hook just calls exposed Sails methods).  Looking into it.

**Comment by sgress454** [comment]
Yup https://github.com/balderdashy/sails/commit/cce4ba9e1198504911857f086d90f4d683474a6c
