### ISSUE TITLE
Certain folders actually do not reload

### ISSUE THREAD

**Issue by Globegitter** [sgress454/sails-hook-autoreload#21]
When I specific my `api/blueprints` or a custom `api/node_modules` folder the hook does trigger when I change a file but actually not register these new files. Only after a server restart the new code works.

Same goes for the configurations.

I suppose for this to work we would need to reload more hooks, right? Any easy way to add that?

**Comment by sgress454** [comment]
To be fair, it's [stated  explicitly](https://github.com/sgress454/sails-hook-autoreload#usage) that the only things that reload are controllers, models and services.  Would love to add to that list.  The tricky part is that there's currently no standard "reload" handler for hooks, so they all require finessing to work with a system like this.

**Comment by Globegitter** [comment]
Thanks for clarifying. I thought something along similar lines was the case just got to have it confirmed. Maybe something for me to tackle at some point :)
