### ISSUE TITLE
Database is dropped when controller is reloaded

### ISSUE THREAD

**Issue by sashasochka** [sgress454/sails-hook-autoreload#22]
Hi, I have this strange behaviour: when I save an updated controller, the same moment my sails-mongo database is simply dropped... in config/models.js I have `migrate: drop`. 

But if the plugin is clever enough to use that setting, I would expect from it calling `config/bootstrap.js` to recreate the db (that's where I setup my database with initial data).

In the end I have to manually restart a server to recreate a database.

**Comment by sgress454** [comment]
This is a case of the plugin _not_ being clever.  It's restarting the ORM, and the ORM is set to "drop", so it's dropping the DB.  There's actually a [pull request](https://github.com/sgress454/sails-hook-autoreload/pull/19) for adding verbiage about this to the README; the only reason I haven't merged it is because I was hoping I (or better yet, someone else) could just fix the behavior so that once lifted, the ORM was set to "migrate: safe"...

**Comment by sashasochka** [comment]
Isn't the fix just a line like 
`sails.config.models.migrate = 'safe'`
?

**Comment by sgress454** [comment]
Could be, you should try it and see, and if it works submit a PR! :)

**Comment by sashasochka** [comment]
PR is here - https://github.com/sgress454/sails-hook-autoreload/pull/23. I didn't do any serious testing but this fixes the issue for me.

**Comment by sashasochka** [comment]
Any updates on PR acceptance?

**Comment by sgress454** [comment]
See [my comment on the PR](https://github.com/sgress454/sails-hook-autoreload/pull/23#issuecomment-99334066).  It fixes your issue, but also basically turns off all model reloading.  I think what you're probably after is `migrate: alter`.

**Comment by dustinbolton** [comment]
Using "migrate: alter" I still experience this issue I believe.  The database tables are not dropped normally when stopping/starting sails.  I am trying safe mode now to see if this addresses the issue.

**Comment by sashasochka** [comment]
What do you think about just re-bootstrapping the app with the code in config/bootstrap.js? That would simulate complete app restart

**Comment by sgress454** [comment]
@dustinbolton `migrate: alter` works by caching all your data, dropping all tables, recreating them and then adding the data back.  So it should do what you need.  

@sochka Re-running `config/bootstrap.js` is partially what this hook is trying to avoid.  We could just lower/re-lift Sails to accomplish all of these tasks, but the process is not always a quick one--it may involve making remote connections, adding fixtures, etc.  

If Sails ever gets a full-on migration system, this hook will happily use that for keeping the database in sync.

**Comment by sgress454** [comment]
Fixed by https://github.com/sgress454/sails-hook-autoreload/pull/27
