### ISSUE TITLE
App crash breaks autoreload

### ISSUE THREAD

**Issue by samholmes** [sgress454/sails-hook-autoreload#26]
When the app crashes (from a syntax error for example), the autoreload functionality doesn't work when I fix the error.

This might be out of the scope of the project, but I can't realistically write code without accidentally writing a syntax error. The purpose of this module should be to speed up development, or am I wrong? The distraction of needing to remember that if the app crashes it will need a restart, kinda defeats the purpose of having an autoreloader in the first place.

**Comment by sgress454** [comment]
You're right, this is out of scope for this project.  It's not meant to replace something like [forever](https://github.com/foreverjs/forever); in fact the two can be used in conjunction if you want.  But you might get more bang for your buck by using a plugin for your code editor that does [syntax checking on the fly](http://www.sublimelinter.com/en/latest/).
