### ISSUE TITLE
I want to help / feature enhencement

### ISSUE THREAD

**Issue by Oldwo1f** [sgress454/sails-hook-autoreload#29]
Hi Sgress

I figured out a way to get the whole application reloaded and multiple tab browser also.

For this i use grunt task with some modules installed globally
- browser-sync    (_gloably installed_)
- nodemon    (_globaly installed_)
- grunt-browser-sync 
- grunt-nodemon
- grunt-concurrent

I would like to share it with sails community by the way of an hook, and i found this module that autoreload without lifting app again, and again. But your module doesnt refresh and syncronize browser tabs and it also doesnt refresh css and client side javascript.

The thing is : i dont really know how to create an hook with grunt tasks inside and globally installed dependencies.

But my  task  " grunt debug " is very handy, maybe it would be nice to add it in sails core to let all developpers have an auto refresh method provided by sails.

Let me know what you think about it.

[browser-sync documentation](http://www.browsersync.io/)

**Comment by sgress454** [comment]
Hi @Oldwo1f--you're right, this hook is purely for reloading the backend, and doesn't handle any front-end tasks.  Your Grunt task sounds great--sounds like the best thing to do would probably be to develop it as a Grunt plugin that could then be easily added to the default task (in `/tasks/register/default.js`) when that functionality was needed.  I agree it would be cool if there was a way to install/configure it via hooks, but at the moment there's no way to add or configure Grunt tasks using the hooks API.

**Comment by Oldwo1f** [comment]
Okey, i ll take a look on how to build grunt-plugin.

Btw, you closed my sails issue before it was resolve. can you please reopen
it. (https://github.com/balderdashy/sails/issues/2947#issuecomment-107288237
)

2015-06-05 21:34 GMT+02:00 sgress454 notifications@github.com:

**Comment by sgress454** [comment]
I closed the other issue because I couldn't re-create it.  But I'll take another look.
