### ISSUE TITLE
Support for services?

### ISSUE THREAD

**Issue by JasonMore** [sgress454/sails-hook-autoreload#3]
Hey I saw in your code that you auto reload controllers, routers, models. What about services? We use those quite a bit in our app. I'd be happy to send a PR for one if you are interested.

**Comment by sgress454** [comment]
Hi @JasonMore, sorry, I don't seem to be getting notifications from this repo.  A PR that reloads services would be great!

**Comment by kevinob11** [comment]
Here is a PR

https://github.com/sgress454/sails-hook-autoreload/pull/10
