### ISSUE TITLE
autoreload views?

### ISSUE THREAD

**Issue by werebeaver** [sgress454/sails-hook-autoreload#35]
Hi, Sgress!

Is it possible with "sails-hook-autoreload" track changes in the templates (views) and clean the cache of templates (views) if it has been changed? 
I am using EJS templates.

**Comment by sgress454** [comment]
@werebeaver Simply refreshing the page should bring in any .ejs template changes in a Sails app.  You can try it with a new app by changing the `homepage.ejs` file and refreshing.
