### ISSUE TITLE
Hability to reload config/locales

### ISSUE THREAD

**Issue by tcury** [sgress454/sails-hook-autoreload#37]
Can you add the feature to reload config/locales files? It's not so good restart app server when these files get changed.

**Comment by sgress454** [comment]
It's only realistic to reload things on a hook-by-hook basis.  So we might be able do something with the i18n hook to reload when locales change, but config in general is a different story.  Sails configuration is stored in files whose names follow a convention, but they're not tied to those names--you could rename your `config/session.js` file `config/foo.js` and it would work just as well, and it would be very hard to tell exactly what configuration was changed.  And some configuration (like `port` or session storage engines) really do require a full server restart.

**Comment by tcury** [comment]
I mean just the locales. When I wrote config/locales the config means just the path. Btw, thanks for the response. Would be nice reload when locales change. Thanks again!

**Comment by tcury** [comment]
Submitted PR #40
