### ISSUE TITLE
Breaks crsf token request

### ISSUE THREAD

**Issue by dottodot** [sgress454/sails-hook-autoreload#39]
After changing something in a controller and it's autoreloaded and I then make a request to get a crsf token the response is empty and I have to restart the app for it to start working again.

**Comment by sgress454** [comment]
Thanks for posting, @dottodot.  I'm unable to reproduce this locally, so I'll need more information:
- Node/NPM version
- Sails version
- Database adapter used
- Session adapter used (if any)

Also, if you can post a link to a repo that would allow me to reproduce the problem, that would help.

**Comment by dottodot** [comment]
Going to close it as I don't seem to have the issue anymore and can't remember if I found the cause or not.
