### ISSUE TITLE
Controllers didn't reload

### ISSUE THREAD

**Issue by dzuluaga** [sgress454/sails-hook-autoreload#45]
Thanks for the hook. I've just tried it, but when I make a change to an existing controller, it logs a message as: `verbose: Detected API change -- reloading controllers / models...`, however new changes aren't applied e.g. adding or removing a `console.log` statement. Am I missing anything?

Thanks,
Diego

**Comment by noahsw** [comment]
Same thing happens for me with services. I see the reload messages but the new code is definitely not there.

```
sails> verbose: Detected API change -- reloading controllers / models...
verbose: Loading the app's models and adapters...
verbose: Loading app models...
verbose: Loading app adapters...
verbose: Starting ORM...
verbose: Loading app services...
verbose: Policy-controller bindings complete!
```

**Comment by sgress454** [comment]
@dzuluaga @noahsw Thanks for trying the hook.  I can't reproduce this issue, so it would be helpful to have more info.  First off, if you could try it with an empty Sails app (`sails new testapp`), just to get a baseline and check that it works on your system at all.  Assuming it does, I'd ideally like to have a link to a repo that I could use to reproduce the problem, along with your:
- Operating system
- Node/NPM version
- Sails version
- Database adapter
- Session adapter (if any)

**Comment by no7dw** [comment]
same happen here, add /remove console.log in controller ,didn't work. but did detected:
verbose: Grunt :: >> File "api/controllers/UserController.js" changed.
verbose: Grunt :: Completed in 0.001s at Tue Mar 15 2016 12:36:40 GMT+0800 (CST) - Waiting...

env:
os: osx 10.11.3
node 0.10.35
sails: 0.11.0
orm: sails-mongo 0.10.x

**Comment by no7dw** [comment]
when I start a new testapp, work fine:

```
verbose: sails-hook-sockets :: connected to Sails admin message bus.
###login
verbose: Detected API change -- reloading controllers / models...
verbose: Loading the app's models and adapters...
verbose: Loading app models...
verbose: Loading app adapters...
verbose: Starting ORM...
  i18n:debug will write to /Users/dengwei/project/sails_demo/config/locales/en.json +13s
  i18n:debug read /Users/dengwei/project/sails_demo/config/locales/en.json for locale: en +1ms
  i18n:debug will write to /Users/dengwei/project/sails_demo/config/locales/es.json +0ms
  i18n:debug read /Users/dengwei/project/sails_demo/config/locales/es.json for locale: es +1ms
  i18n:debug will write to /Users/dengwei/project/sails_demo/config/locales/fr.json +0ms
  i18n:debug read /Users/dengwei/project/sails_demo/config/locales/fr.json for locale: fr +0ms
  i18n:debug will write to /Users/dengwei/project/sails_demo/config/locales/de.json +1ms
  i18n:debug read /Users/dengwei/project/sails_demo/config/locales/de.json for locale: de +0ms
verbose: Loading app services...
verbose: Policy-controller bindings complete!
*****###login
```

---last line change

do some experiment:

turn out that the reason why can not reload, which written in README.md
sails modules version must >= 0.11.0
i use sails version 0.11.0, and had use sails node_modules also 0.11.0, which i use sails in 0.10.6 in node_modules

**Comment by sgress454** [comment]
Thanks @no7dw -- yup, always important to make sure Sails is at the version you think it is!
