### ISSUE TITLE
unhandled error event

### ISSUE THREAD

**Issue by samundrak** [sgress454/sails-hook-autoreload#52]
![image](https://cloud.githubusercontent.com/assets/3079452/12530034/354f9d6e-c1f8-11e5-9648-bc9fa56ad80c.png)

I am facing this problem , i just installed this module and added autoreload file in config as u mentioned in example ?

**Comment by sgress454** [comment]
Hi @samundrak.  See http://stackoverflow.com/questions/22475849/node-js-error-enospc for more info on the ENOSPC error.
