### ISSUE TITLE
Error on sails v0.12.0

### ISSUE THREAD

**Issue by dottodot** [sgress454/sails-hook-autoreload#53]
Getting the following error after updating to sails 0.12.0

> TypeError: sails.hooks.controllers.loadAndRegisterControllers is not a function

**Comment by jesperborgstrup** [comment]
Confirmed. To expand a bit, using Sails 0.12.0 and sails-hook-autoreload 0.11.5, the following error and stack trace are printed out:

```
/app/node_modules/sails-hook-autoreload/index.js:63
        sails.hooks.controllers.loadAndRegisterControllers(function() {
                                ^

TypeError: sails.hooks.controllers.loadAndRegisterControllers is not a function
    at FSWatcher.<anonymous> (/app/node_modules/sails-hook-autoreload/index.js:63:33)
    at complete (/app/node_modules/lodash/index.js:7697:25)
    at delayed [as _onTimeout] (/app/node_modules/lodash/index.js:7707:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by jesperborgstrup** [comment]
The following commit in Sails has removed the `loadAndRegisterControllers` function from the `controllers` hook object, and moved it into a separate file:
https://github.com/balderdashy/sails/commit/65346fd2aca19c19a186d12824f441f7102378f3

**Comment by justerhan** [comment]
@jesperborgstrup Guessing you can just change loadAndRegisterControllers(...) to initialize(...) in the line of code specified at the top of the stack.

**Comment by sgress454** [comment]
@dottodot @jesperborgstrup Thanks for pointing this out.  When I first put this hook together it was more of a demonstration of the new API for extending Sails, so I didn't give much thought to the fact that I was using a method that was clearly marked `@private`.  I'll patch this up and put out a new minor release, but beware if you are trying to use that method in your own projects, for whatever strange reason.

@bountyx You should never call a hook's `initialize()` method directly; they're meant to be called by Sails core.  If a hook is meant to be re-loadable, it should offer a public method to do so (looking into this for the controllers hook).  In this case for example, calling `.initialize()` again would bind another handler for the `route:typeUnknown` event, which would mean routes would get bound twice every time the router was flushed (bad!).

**Comment by sgress454** [comment]
Actually I misspoke--there's nothing to be done in the hook itself, but we'll be putting out a patch release of Sails that will get this working again as-is until we introduce a public `.reload()` method for the controllers hook.

**Comment by sumon444** [comment]
I'm having the same issue on sails v0.12.0. any undate on this?

**Comment by jesperborgstrup** [comment]
It looks like the `loadAndRegisterControllers` have been re-exposed for now (see commit https://github.com/balderdashy/sails/commit/0ba78296047874debd33ce62588e97c371b7138c in `master` branch).
Update to Sails v.0.12.1 to (re)use this feature.

**EDIT:** After updating to Sails v0.12.1, this is not an issue anymore.

**NOTE:** The commit message to the above commit in Sails is 

> `loadAndRegisterControllers` used to be defined directly on the hook object, but was removed when it was moved to a different file.  A couple of apps in the wild are relying on it, so we'll re-introduce it for now, but it really needs to be wrapped in a public `.reload()` method.

**Comment by sgress454** [comment]
Right on--sorry for forgetting to post in here.  We've re-exposed the private API method for now as of Sails v0.12.1, as we ponder the `.reload()` API for Sails hooks in general.  So as of v0.12.1 this should be good to go!
