### ISSUE TITLE
Be able to set i18n reload optional in config

### ISSUE THREAD

**Issue by Fr33maan** [sgress454/sails-hook-autoreload#54]
Hi,

I'm using the module since the first time I lifted a sails app and I love it ! 

Yesterday I started to use an awesome yeoman scaffold for sails called [sails-rest-api](https://github.com/ghaiklor/generator-sails-rest-api).

They decided to remove internationalization and it creates a conflict with sails-hook-autoreload.

To solve my problem, I just commented the line 109 on the index.js in my node_modules but I usually prefer to have a permanent solution that I can use agin in another project. 
It will also make your module compatible with this awesome scaffold !

``` javascript
// Reload locales
// sails.hooks.i18n.initialize(function() {});
```

Thanks for your work ! :)

**Comment by Fr33maan** [comment]
It already has been released on npm ? I just installed the module on a new project and still have the error.

**Comment by disciple-dev** [comment]
@sgress454 If you find a moment to publish the latest changes on npm, I'd be eternally grateful.

**Comment by sgress454** [comment]
Done!
