### ISSUE TITLE
'sails console' ignores 'migrate:safe' config and drops db tables on autoreload.

### ISSUE THREAD

**Issue by vitkorbut** [sgress454/sails-hook-autoreload#72]

**Comment by sgress454** [comment]
@korbutvitaliy have you read the [usage section](https://github.com/sgress454/sails-hook-autoreload#usage) which describes how migrations work with autoreload?

**Comment by vitkorbut** [comment]
Right.
module.exports.autoreload = {
  overrideMigrateSetting: false,
