### ISSUE TITLE
[Critical bug]This hook completely breaks the app if you have more than 1 datastore in sails v1/waterline v0.13

### ISSUE THREAD

**Issue by megakoresh** [sgress454/sails-hook-autoreload#74]
I have 2 datastores - default is MariaDb and the other is mongo, used for one model (set in model file). When autoreload happens, it completely breaks any further database interactions with the following error:
```
error: AdapterError: Unexpected error from database adapter: Could not run `join` due to 2 validation errors:
  • `datastore` is a required input- but it was not defined.
  • `models` is a required input- but it was not defined.
    ....
```
Any database interactions are afterwards broken until application is restarted.
To repro

1. Make 2 datastores - 1 mongo and 1 mysql
2. Set mysql as default
3. Set mongo one for some model inside the model file
4. Migrations are 'alter', the `overrideMigrationSetting` config doesn't affect this bug by the looks of it.
5. Perform some db operation
6. Make change to controller/model/whatever hook watches
7. Do another db operation when the reload completes
8. Get the bug

**Comment by sgress454** [comment]
@megakoresh  Thanks for using Sails!  We've decided to end official support for this hook, as detailed in the [end-of-life notice](https://github.com/sgress454/sails-hook-autoreload#skull-skull-skull-official-end-of-life-notice-skull-skull-skull).  If you're interested in taking over, please contact [@sgress454](@sgress454).

**Comment by Fr33maan** [comment]
Sorry for this one but I won't dive so deeply in the hook. If you absolutely want to use this configuration with the hook then feel free to PR.
