### ISSUE TITLE
Release to npm

### ISSUE THREAD

**Issue by Fr33maan** [sgress454/sails-hook-autoreload#76]
The version on npm is not the one for sails 1.0.
It still checks for sails.hooks.controllers to be true while this condition has been swiped out from the new version.
It makes the hook unusable, please @sgress454 publish the new version to npm

**Comment by Fr33maan** [comment]
Of course it's possible to install it via `npm i -S sgress454/sails-hook-autoreload#master`

**Comment by sgress454** [comment]
@l1br3 The 1.0.0 release has been out for quite some time; that's the Sails 1.0-compatible release.  You can get the Sails v0.12 release with `npm install sails-hook-autoreload@for-sails-12`

**Comment by Fr33maan** [comment]
Ho yes it's my cache fault ! Thanks
