### ISSUE TITLE
npm collaborator list

### ISSUE THREAD

**Issue by Fr33maan** [sgress454/sails-hook-autoreload#77]
@sgress454 While we are in the "finding maintainers" process, could you add [me](https://www.npmjs.com/~prisonier) to the collaborator list please ?
Thanks in advance

**Comment by sgress454** [comment]
@l1br3 Let's keep the ownership with me for the time being.  Just ping me when you need a release so I can take a look.  After a few successful releases we can talk about adding you as a maintainer on the package.  Thanks!

**Comment by Fr33maan** [comment]
sounds perfect !
